events {}

http {

    upstream auth_service {
        server auth-service:5000;
    }

    upstream product_service {
        server product-service:5000;
    }

    upstream order_service {
        server order-service:5000;
    }

    server {

        listen 80;

        location /auth/ {
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /products/ {
            proxy_pass http://product_service/products;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /orders/ {
            proxy_pass http://order_service/orders;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            return 200 "NGINX Gateway Healthy\n";
            add_header Content-Type text/plain;
        }
    }
}
